<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>AbpAdmin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Driver" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Volo.Abp.Core" />
  </ItemGroup>

</Project>
